-- SCRIPT DE EXPANSÃO DE COLUNAS - SAAS BANCADAS
-- Este script adiciona todas as colunas originais das bancadas (Access) e do Relatório (CSV) ao Supabase.

-- 1. Tabela: data (Campos Técnicos do Access)
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Pres loss value" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Pres loss conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Final conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error Qmax" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error Qmin" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Name" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "G Size" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Approval Number" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Type of connection" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Qmin" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Qmax" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Qt" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Volume of metering chamber" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Test via" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Test Index control via" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Without index control" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "With index control" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Pulse value without" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Pulse value with" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Direction" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error limits" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Note" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Nominal width" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Q single" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Mech pres loss" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Total pres loss" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Type of Meter" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Meter Position" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Manufacturer" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Correction Gear Table" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Date of Make" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Date of Calibration" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Customer" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Order Number" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Calibration Validity" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Tester" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Test procedure" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Unit of Measurement" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Uref" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Current Reading" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "State" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Repeatability result" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Repeatability conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Repeatability0 result" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Repeatability0 conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Gear NO" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Hole NO" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Gear Color" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "WME result" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "WME conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "RejectionId" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 02Qmax" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error Qnom" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 05Qnom" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 01Qnom" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 005Qnom" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Qnom" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Accuracy" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Additional Device" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Mech pres loss value" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Mech pres loss conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Pmax" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "BenchID" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Maximum permission error" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Test bench" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 07Qmax" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 04Qmax" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 01Qmax" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Error 3Qmin" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Gear Result" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Above Error result" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Above Error conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Below Error result" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Below Error conclusion" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Intelligent meter" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Correct TP" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Basic temperature" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Basic pressure" NUMERIC;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Verification Procedure" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Product code" TEXT;
ALTER TABLE data ADD COLUMN IF NOT EXISTS "Set Temperature" NUMERIC;

-- 2. Tabela: full_data (Curvas Técnicas)
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "NO" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Name" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Type" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Test point" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Sequence" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Standard flow" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Test time" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Humidity" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Container pressure" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Container temperature" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Standard volume" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Meter pressure" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Meter temperature" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Meter volume" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Error" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Average Error" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Repeatability" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pressure Loss" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Average Pressure Loss" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Error limit from" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Error limit up to" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pressure loss limit" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Valve status" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "At above" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Primary error" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Average Primary error" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Labpressure" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Labtemperature" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "UMeterError" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "KMeterError" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pressure Loss Max" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pressure Loss Min" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "StepStatus" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Start Reading" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Finish Reading" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Flow Plot" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Start Time" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Finish Time" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Standard flow0" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "ddCd" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Left Pressure" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Left Temperature" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Right Pressure" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Right Temperature" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Repeatability Limit" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Repeatability0 Limit" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Repeatability0" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "WME K" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "ReqFlowRate" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "MeterPulses" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pressure Loss Code" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "ddCd2" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Container pressure2" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Container temperature2" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pulse Value" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Cals Mode" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Error Correction" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Cycle Volume" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Error by Cycle" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Cycle time" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Cycle Volume Set" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Instrument flow" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Instrument Pressure" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Instrument Temperature" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pressure Error" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Temperature Error" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Last Reading" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Current Reading" NUMERIC;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Test mode" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "UsedNozzles" TEXT;
ALTER TABLE full_data ADD COLUMN IF NOT EXISTS "Pulse Sensor" TEXT;

-- 3. Tabela: vinculo_lacre (Relatório Comercial)
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "COD. LACRE" TEXT;
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "LACRE" TEXT;
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "DATA VINCULO" TEXT;
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "SEQ. LOTE" TEXT;
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "TIPO" TEXT;
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "LOTE PRODUTO" TEXT;
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "COD. INMETRO" TEXT;
ALTER TABLE vinculo_lacre ADD COLUMN IF NOT EXISTS "LOTE INMETRO" TEXT;

-- 4. Adição de campo de Mapeamento de Colunas na app_config
-- Isso permite traduzir os nomes originais acima para nomes amigáveis no frontend.
ALTER TABLE app_config ADD COLUMN IF NOT EXISTS column_labels JSONB DEFAULT '{}'::jsonb;

-- 5. Reconstrução da Visão Global Unificada (global_uniao)
-- Usamos seleção explícita para evitar conflitos de nomes (Ex: ID Mark existe em ambas as tabelas)
DROP VIEW IF EXISTS global_uniao;
CREATE OR REPLACE VIEW global_uniao AS
SELECT 
    d.*, 
    -- Campos técnicos da full_data
    fd."Standard flow", fd."Test time", fd."Error", fd."Pressure Loss", 
    fd."Meter pressure", fd."Meter temperature", fd."Standard volume", 
    fd."Meter volume", fd."Humidity", fd."Start Time", fd."Finish Time",
    -- Campos do Relatório CSV
    vl."LACRE", vl."LOTE PRODUTO", vl."DATA VINCULO", vl."TIPO", 
    vl."COD. LACRE", vl."SEQ. LOTE", vl."COD. INMETRO", vl."LOTE INMETRO"
FROM data d
LEFT JOIN full_data fd ON (d."ID Mark" = fd."ID Mark" AND d.bancada_id = fd.bancada_id)
LEFT JOIN vinculo_lacre vl ON (d."Meter Number" = vl."LOTE PRODUTO");

GRANT SELECT ON global_uniao TO anon;
GRANT SELECT ON global_uniao TO authenticated;

-- 6. Índices de Performance para a Visão Global (ESSENCIAL para 400k+ registros)
CREATE INDEX IF NOT EXISTS idx_data_id_mark_bancada ON data ("ID Mark", bancada_id);
CREATE INDEX IF NOT EXISTS idx_full_data_id_mark_bancada ON full_data ("ID Mark", bancada_id);
CREATE INDEX IF NOT EXISTS idx_data_meter_number ON data ("Meter Number");
CREATE INDEX IF NOT EXISTS idx_vinculo_lacre_lote_produto ON vinculo_lacre ("LOTE PRODUTO");
CREATE INDEX IF NOT EXISTS idx_data_save_time ON data ("Save time" DESC);
