-- 1. Criar a tabela 'data' para registros consolidados
CREATE TABLE IF NOT EXISTS public.data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID Mark" TEXT UNIQUE NOT NULL, -- Chave única da bancada
    bancada_id INTEGER NOT NULL,
    "Meter Number" TEXT,
    "Error conclusion" TEXT,
    "Save time" TEXT,
    status TEXT DEFAULT 'processed',
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    sync_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar a tabela 'full_data' para logs detalhados
CREATE TABLE IF NOT EXISTS public.full_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID Mark" TEXT UNIQUE NOT NULL,
    bancada_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    raw_payload JSONB, -- Para guardar dados complexos
    sync_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Habilitar o Realtime para monitoramento automático (Seguro para rodar múltiplas vezes)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'data') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.data;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'full_data') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.full_data;
    END IF;
END $$;

-- 4. Criar política de leitura pública (Seguro para rodar múltiplas vezes)
ALTER TABLE public.data ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'data' AND policyname = 'Leitura pública para todos') THEN
        CREATE POLICY "Leitura pública para todos" ON public.data FOR SELECT USING (true);
    END IF;
END $$;

ALTER TABLE public.full_data ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'full_data' AND policyname = 'Leitura pública para todos') THEN
        CREATE POLICY "Leitura pública para todos" ON public.full_data FOR SELECT USING (true);
    END IF;
END $$;

-- 5. Índices de Performance (Essencial para datasets > 100k)
CREATE INDEX IF NOT EXISTS idx_data_bancada_timestamp ON public.data (bancada_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_full_data_bancada_timestamp ON public.full_data (bancada_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_data_id_mark ON public.data ("ID Mark");
CREATE INDEX IF NOT EXISTS idx_full_data_id_mark ON public.full_data ("ID Mark");
