-- ═══════════════════════════════════════════════════════════════════
--  SaaS Bancadas — Schema Setup V2 (Composite ID)
--  Execute este script no SQL Editor do Supabase.
--  É seguro rodar múltiplas vezes (usa IF NOT EXISTS e IF EXISTS).
-- ═══════════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────────────────────────
-- 1. Tabela 'data' — Registros principais de cada bancada
-- ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- composite_id = "{bancada_id}_{ID Mark}" — garante unicidade por bancada
    composite_id TEXT UNIQUE NOT NULL,
    "ID Mark" TEXT NOT NULL,
    bancada_id INTEGER NOT NULL,
    "Meter Number" TEXT,
    "Error conclusion" TEXT,
    "Save time" TEXT,
    status TEXT DEFAULT 'processed',
    timestamp TIMESTAMPTZ,
    -- sync_at = momento da sincronização (usado para status Online/Idle/Offline)
    sync_at TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────────
-- 2. Tabela 'full_data' — Dados técnicos completos em JSONB
-- ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.full_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    composite_id TEXT UNIQUE NOT NULL,
    "ID Mark" TEXT NOT NULL,
    bancada_id INTEGER NOT NULL,
    raw_payload JSONB,
    -- sync_at = momento da sincronização
    sync_at TIMESTAMPTZ DEFAULT NOW()
);

-- ──────────────────────────────────────────────────────────────────
-- 3. MIGRAÇÃO — Adicionar composite_id em tabelas já existentes
--    (Execute apenas se as tabelas já existiam sem essa coluna)
-- ──────────────────────────────────────────────────────────────────
DO $$
BEGIN
    -- Adicionar composite_id em 'data' se não existir
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='data' AND column_name='composite_id'
    ) THEN
        ALTER TABLE public.data ADD COLUMN composite_id TEXT;
        -- Preencher composite_id para registros existentes
        UPDATE public.data SET composite_id = bancada_id::TEXT || '_' || "ID Mark"
        WHERE composite_id IS NULL;
        -- Remover duplicatas antes de criar a constraint
        DELETE FROM public.data a
        USING public.data b
        WHERE a.id < b.id AND a.composite_id = b.composite_id;
        -- Adicionar constraint UNIQUE
        ALTER TABLE public.data ADD CONSTRAINT data_composite_id_unique UNIQUE (composite_id);
        RAISE NOTICE 'composite_id adicionado à tabela data';
    END IF;
    
    -- Adicionar composite_id em 'full_data' se não existir
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='full_data' AND column_name='composite_id'
    ) THEN
        ALTER TABLE public.full_data ADD COLUMN composite_id TEXT;
        UPDATE public.full_data SET composite_id = bancada_id::TEXT || '_' || "ID Mark"
        WHERE composite_id IS NULL;
        DELETE FROM public.full_data a
        USING public.full_data b
        WHERE a.id < b.id AND a.composite_id = b.composite_id;
        ALTER TABLE public.full_data ADD CONSTRAINT full_data_composite_id_unique UNIQUE (composite_id);
        RAISE NOTICE 'composite_id adicionado à tabela full_data';
    END IF;
END $$;

-- ──────────────────────────────────────────────────────────────────
-- 4. Remover a antiga constraint UNIQUE em "ID Mark" se existir
--    (Era o bug: bancadas diferentes com mesmo ID Mark se sobrescreviam)
-- ──────────────────────────────────────────────────────────────────
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.data'::regclass AND conname = 'data_ID Mark_key'
    ) THEN
        ALTER TABLE public.data DROP CONSTRAINT "data_ID Mark_key";
        RAISE NOTICE 'Constraint antiga em ID Mark removida da tabela data';
    END IF;
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.full_data'::regclass AND conname = 'full_data_ID Mark_key'
    ) THEN
        ALTER TABLE public.full_data DROP CONSTRAINT "full_data_ID Mark_key";
        RAISE NOTICE 'Constraint antiga em ID Mark removida da tabela full_data';
    END IF;
END $$;

-- ──────────────────────────────────────────────────────────────────
-- 5. Realtime
-- ──────────────────────────────────────────────────────────────────
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'data') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.data;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'full_data') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.full_data;
    END IF;
END $$;

-- ──────────────────────────────────────────────────────────────────
-- 6. Row Level Security
-- ──────────────────────────────────────────────────────────────────
ALTER TABLE public.data ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'data' AND policyname = 'Leitura pública para todos') THEN
        CREATE POLICY "Leitura pública para todos" ON public.data FOR SELECT USING (true);
    END IF;
END $$;

ALTER TABLE public.full_data ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'full_data' AND policyname = 'Leitura pública para todos') THEN
        CREATE POLICY "Leitura pública para todos" ON public.full_data FOR SELECT USING (true);
    END IF;
END $$;

-- ──────────────────────────────────────────────────────────────────
-- 7. Índices de Performance
-- ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_data_bancada_sync ON public.data (bancada_id, sync_at DESC);
CREATE INDEX IF NOT EXISTS idx_data_bancada_timestamp ON public.data (bancada_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_data_composite ON public.data (composite_id);
CREATE INDEX IF NOT EXISTS idx_full_data_bancada_sync ON public.full_data (bancada_id, sync_at DESC);
CREATE INDEX IF NOT EXISTS idx_full_data_composite ON public.full_data (composite_id);
