-- 1. Criar a tabela 'data' para registros consolidados
CREATE TABLE IF NOT EXISTS public.data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID Mark" TEXT UNIQUE NOT NULL, -- Chave única da bancada
    bancada_id INTEGER NOT NULL,
    "Meter Number" TEXT,
    "Error conclusion" TEXT,
    "Save time" TEXT,
    status TEXT DEFAULT 'processed',
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    sync_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar a tabela 'full_data' para logs detalhados
CREATE TABLE IF NOT EXISTS public.full_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID Mark" TEXT NOT NULL,
    bancada_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    raw_payload JSONB, -- Para guardar dados complexos
    sync_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Habilitar o Realtime para monitoramento automático
ALTER PUBLICATION supabase_realtime ADD TABLE public.data;
ALTER PUBLICATION supabase_realtime ADD TABLE public.full_data;

-- 4. Criar política de leitura pública (opcional, dependendo da sua segurança)
ALTER TABLE public.data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública para todos" ON public.data FOR SELECT USING (true);

ALTER TABLE public.full_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública para todos" ON public.full_data FOR SELECT USING (true);
