-- 1. Add 'note' column to main data table
ALTER TABLE public.data ADD COLUMN IF NOT EXISTS note TEXT;

-- 2. Add 'benches_config' and 'csv_config' to app_config
ALTER TABLE public.app_config ADD COLUMN IF NOT EXISTS benches_config JSONB DEFAULT '[]';
ALTER TABLE public.app_config ADD COLUMN IF NOT EXISTS csv_config JSONB DEFAULT ''{"path": "C:\\Users\\User\\Documents\\GitHub\\Saas_Bancadas\\Relatorio.csv", "last_sync": null}'';

-- 3. Create 'vinculo_lacre' table for CSV data
CREATE TABLE IF NOT EXISTS public.vinculo_lacre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lacre TEXT UNIQUE NOT NULL,
    lote_produto TEXT,
    data_vinculo TEXT,
    tipo TEXT,
    cod_lacre TEXT,
    sync_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Set initial Benches Configuration (User mapping)
UPDATE public.app_config SET benches_config = ''[
    {"id": 1, "name": "Bancada 1", "paths": [{"data": "C:\\Users\\User\\Documents\\BD\\database1\\Data.accdb", "fullData": "C:\\Users\\User\\Documents\\BD\\database1\\Full Data.accdb"}]},
    {"id": 2, "name": "Bancada 2", "paths": [
        {"data": "C:\\Users\\User\\Documents\\BD\\database2\\Data.accdb", "fullData": "C:\\Users\\User\\Documents\\BD\\database2\\Full Data.accdb"},
        {"data": "C:\\Users\\User\\Documents\\BD\\database4\\Data.accdb", "fullData": "C:\\Users\\User\\Documents\\BD\\database4\\Full Data.accdb"}
    ]},
    {"id": 3, "name": "Bancada 3", "paths": [{"data": "C:\\Users\\User\\Documents\\BD\\database3\\Data.accdb", "fullData": "C:\\Users\\User\\Documents\\BD\\database3\\Full Data.accdb"}]},
    {"id": 4, "name": "Bancada 4", "paths": [{"data": "C:\\Users\\User\\Documents\\BD\\database5\\Data.accdb", "fullData": "C:\\Users\\User\\Documents\\BD\\database5\\Full Data.accdb"}]}
]'' WHERE id = 1;

-- 5. Create the "Global Uniao" View (All Data + All Fields + All Benches + Lote)
CREATE OR REPLACE VIEW public.global_uniao AS
SELECT 
    d.id,
    d.composite_id,
    d."ID Mark",
    d.bancada_id,
    d."Meter Number",
    d."Error conclusion",
    d."Save time",
    d.timestamp,
    d.sync_at,
    d.note,
    fd.raw_payload as technical_data,
    vl.lote_produto,
    vl.data_vinculo as csv_vinculo_date
FROM public.data d
LEFT JOIN public.full_data fd ON d.composite_id = fd.composite_id
LEFT JOIN public.vinculo_lacre vl ON d."Meter Number" = vl.lacre;

-- Permissions
GRANT SELECT ON public.vinculo_lacre TO anon, authenticated;
GRANT SELECT ON public.global_uniao TO anon, authenticated;
